# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_pickup', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prices', models.ManyToManyField(to='order_manager.Price')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dl', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='order_manager.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_dl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_manager.UserAccount'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='menu',
            field=models.ManyToManyField(to='order_manager.Product'),
        ),
    ]
