# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_acct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
