# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_auto_20160603_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_pickup', models.DateTimeField()),
                ('products', models.ManyToManyField(to='order_manager.Product')),
                ('user_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_manager.UserAccount')),
            ],
        ),
    ]
